/* eslint-disable */
/**
 * OAI Specification example for Polymorphism
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { Reptile, SnakeAllOf } from './';

/**
 *
 * @interface Snake
 */
export interface Snake extends Reptile {
  /**
   *
   * @type {boolean}
   * @memberof Snake
   */
  hasLegs?: boolean;
}

export const SnakeModel: GenericModel = {
  classname: 'Snake',
  type: 'generic',
  parent: 'Reptile',
  vars: {
    hasLegs: {
      name: 'hasLegs',
      baseName: 'hasLegs',
      datatype: 'boolean',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: true,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    hasLegs: 'hasLegs',
  },
};
