/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { ComplexModel, ExampleModel, ModelWithAdditionalProperties } from './';

/**
 *
 * @interface FreeformObjectTypes
 */
export interface FreeformObjectTypes {
  /**
   *
   * @type {ExampleModel}
   * @memberof FreeformObjectTypes
   */
  exampleModel?: ExampleModel;

  /**
   *
   * @type {ModelWithAdditionalProperties}
   * @memberof FreeformObjectTypes
   */
  modelWithAdditionalProperties?: ModelWithAdditionalProperties;

  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof FreeformObjectTypes
   */
  modelWithStringToStringMapping?: { [key: string]: string };

  /**
   *
   * @type {{ [key: string]: ComplexModel; }}
   * @memberof FreeformObjectTypes
   */
  modelWithStringToModelMapping?: { [key: string]: ComplexModel };

  /**
   *
   * @type {ComplexModel}
   * @memberof FreeformObjectTypes
   */
  complexModel?: ComplexModel;
}

export const FreeformObjectTypesModel: GenericModel = {
  classname: 'FreeformObjectTypes',
  type: 'generic',
  parent: undefined,
  vars: {
    exampleModel: [
      'exampleModel', // name
      'ExampleModel', // baseName
      'ExampleModel', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      true, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    modelWithAdditionalProperties: [
      'modelWithAdditionalProperties', // name
      'ModelWithAdditionalProperties', // baseName
      'ModelWithAdditionalProperties', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    modelWithStringToStringMapping: [
      'modelWithStringToStringMapping', // name
      'ModelWithStringToStringMapping', // baseName
      '{ [key: string]: string; }', // datatype
      false, // required
      'string', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      true, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    modelWithStringToModelMapping: [
      'modelWithStringToModelMapping', // name
      'ModelWithStringToModelMapping', // baseName
      '{ [key: string]: ComplexModel; }', // datatype
      false, // required
      'ComplexModel', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      true, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      true, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    complexModel: [
      'complexModel', // name
      'ComplexModel', // baseName
      'ComplexModel', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      true, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    exampleModel: 'ExampleModel',
    modelWithAdditionalProperties: 'ModelWithAdditionalProperties',
    modelWithStringToStringMapping: 'ModelWithStringToStringMapping',
    modelWithStringToModelMapping: 'ModelWithStringToModelMapping',
    complexModel: 'ComplexModel',
  },
};
