/* eslint-disable */
/**
 * Example API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { ComplexModel, ExampleModel, ModelWithAdditionalProperties } from './';

/**
 *
 * @interface FreeformObjectTypes
 */
export interface FreeformObjectTypes {
  /**
   *
   * @type {ExampleModel}
   * @memberof FreeformObjectTypes
   */
  exampleModel?: ExampleModel;

  /**
   *
   * @type {ModelWithAdditionalProperties}
   * @memberof FreeformObjectTypes
   */
  modelWithAdditionalProperties?: ModelWithAdditionalProperties;

  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof FreeformObjectTypes
   */
  modelWithStringToStringMapping?: { [key: string]: string };

  /**
   *
   * @type {{ [key: string]: ComplexModel; }}
   * @memberof FreeformObjectTypes
   */
  modelWithStringToModelMapping?: { [key: string]: ComplexModel };

  /**
   *
   * @type {ComplexModel}
   * @memberof FreeformObjectTypes
   */
  complexModel?: ComplexModel;
}

export const FreeformObjectTypesModel: GenericModel = {
  classname: 'FreeformObjectTypes',
  type: 'generic',
  parent: undefined,
  vars: {
    exampleModel: {
      name: 'exampleModel',
      baseName: 'ExampleModel',
      datatype: 'ExampleModel',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: true,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    modelWithAdditionalProperties: {
      name: 'modelWithAdditionalProperties',
      baseName: 'ModelWithAdditionalProperties',
      datatype: 'ModelWithAdditionalProperties',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    modelWithStringToStringMapping: {
      name: 'modelWithStringToStringMapping',
      baseName: 'ModelWithStringToStringMapping',
      datatype: '{ [key: string]: string; }',
      required: false,
      itemsDataType: 'string',
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: true,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: true,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    modelWithStringToModelMapping: {
      name: 'modelWithStringToModelMapping',
      baseName: 'ModelWithStringToModelMapping',
      datatype: '{ [key: string]: ComplexModel; }',
      required: false,
      itemsDataType: 'ComplexModel',
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: true,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: true,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: true,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    complexModel: {
      name: 'complexModel',
      baseName: 'ComplexModel',
      datatype: 'ComplexModel',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: true,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    exampleModel: 'ExampleModel',
    modelWithAdditionalProperties: 'ModelWithAdditionalProperties',
    modelWithStringToStringMapping: 'ModelWithStringToStringMapping',
    modelWithStringToModelMapping: 'ModelWithStringToModelMapping',
    complexModel: 'ComplexModel',
  },
};
