openapi: 3.0.0
info:
  version: 1.0.0
  title: Basic
paths:
  /sample:
    get:
      responses:
        '200':
          description: successful operation
          content:
            'application/json':
              schema:
                type: object
                properties:
                  hello:
                    type: string