/* eslint-disable */
/**
 * Elm generator test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { Enum, Primitive } from './';

/**
 * Model with arrays
 * @interface ModelArray
 */
export interface ModelArray {
  /**
   *
   * @type {Array<string>}
   * @memberof ModelArray
   */
  array: Array<string>;

  /**
   *
   * @type {Array<Array<string>>}
   * @memberof ModelArray
   */
  arrayOfArray: Array<Array<string>>;

  /**
   *
   * @type {Array<Primitive>}
   * @memberof ModelArray
   */
  arrayOfPrimitve?: Array<Primitive>;

  /**
   *
   * @type {Array<Enum>}
   * @memberof ModelArray
   */
  arrayOfEnum?: Array<Enum>;
}

export const ModelArrayModel: GenericModel = {
  classname: 'ModelArray',
  type: 'generic',
  parent: undefined,
  vars: {
    array: [
      'array', // name
      'array', // baseName
      'Array&lt;string&gt;', // datatype
      true, // required
      'string', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      true, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    arrayOfArray: [
      'arrayOfArray', // name
      'arrayOfArray', // baseName
      'Array&lt;Array&lt;string&gt;&gt;', // datatype
      true, // required
      'Array&lt;string&gt;', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      true, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    arrayOfPrimitve: [
      'arrayOfPrimitve', // name
      'arrayOfPrimitve', // baseName
      'Array&lt;Primitive&gt;', // datatype
      false, // required
      'Primitive', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      true, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    arrayOfEnum: [
      'arrayOfEnum', // name
      'arrayOfEnum', // baseName
      'Array&lt;Enum&gt;', // datatype
      false, // required
      'Enum', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      true, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    array: 'array',
    arrayOfArray: 'arrayOfArray',
    arrayOfPrimitve: 'arrayOfPrimitve',
    arrayOfEnum: 'arrayOfEnum',
  },
};
