/* eslint-disable */
/**
 * rust-server-test
 * This spec is for testing rust-server-specific things
 *
 * The version of the OpenAPI document: 2.3.4
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { ANullableContainerModel } from './models/ANullableContainer';
import { AllOfObjectModel } from './models/AllOfObject';
import { BaseAllOfModel } from './models/BaseAllOf';
import { GetYamlResponseModel } from './models/GetYamlResponse';
import { InlineObjectModel } from './models/InlineObject';
import { ObjectOfObjectsModel } from './models/ObjectOfObjects';
import { ObjectOfObjectsInnerModel } from './models/ObjectOfObjectsInner';

export const typeSerializer = new TypeSerializer({
  ANullableContainer: ANullableContainerModel,
  AllOfObject: AllOfObjectModel,
  BaseAllOf: BaseAllOfModel,
  GetYamlResponse: GetYamlResponseModel,
  InlineObject: InlineObjectModel,
  ObjectOfObjects: ObjectOfObjectsModel,
  ObjectOfObjectsInner: ObjectOfObjectsInnerModel,
});
