/* eslint-disable */
/**
 * ping test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { AnyValueModelModel } from './models/AnyValueModel';
import { AnyValueModelInlineModel } from './models/AnyValueModelInline';

export const typeSerializer = new TypeSerializer({
  AnyValueModel: AnyValueModelModel,
  AnyValueModelInline: AnyValueModelInlineModel,
});
