import * as defaultApi from './DefaultApi';
export { defaultApi };
import * as group4Api from './Group4Api';
export { group4Api };
import * as group5Api from './Group5Api';
export { group5Api };
import * as tag1Api from './Tag1Api';
export { tag1Api };
import * as tag2Api from './Tag2Api';
export { tag2Api };
