openapi: 3.0.0
info:
  version: 1.0.0
  title: Posts
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      type: object
      properties:
        userId:
          type: number
        id:
          type: number
        title:
          type: string
        body:
          type: string
      required: [ userId, id, title, body ]