/* eslint-disable */
/**
 * EmailExample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { PersonWithEmailModel } from './models/PersonWithEmail';

export const typeSerializer = new TypeSerializer({
  PersonWithEmail: PersonWithEmailModel,
});
