/* eslint-disable */
/**
 * The Wordnik Public API
 * **Wordnik has an API, and you\'re invited.** The Wordnik API lets you request definitions, example sentences, spelling suggestions,  related words like synonyms and antonyms, phrases containing a given word, word  autocompletion, random words, words of the day, and much more
 *
 * The version of the OpenAPI document: 4.0.1
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { Example, Facet } from './';

/**
 *
 * @interface ExampleSearchResults
 */
export interface ExampleSearchResults {
  /**
   *
   * @type {Array<Facet>}
   * @memberof ExampleSearchResults
   */
  facets?: Array<Facet>;

  /**
   *
   * @type {Array<Example>}
   * @memberof ExampleSearchResults
   */
  examples?: Array<Example>;
}

export const ExampleSearchResultsModel: GenericModel = {
  classname: 'ExampleSearchResults',
  type: 'generic',
  parent: undefined,
  vars: {
    facets: {
      name: 'facets',
      baseName: 'facets',
      datatype: 'Array&lt;Facet&gt;',
      required: false,
      itemsDataType: 'Facet',
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: true,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: true,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    examples: {
      name: 'examples',
      baseName: 'examples',
      datatype: 'Array&lt;Example&gt;',
      required: false,
      itemsDataType: 'Example',
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: true,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: true,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    facets: 'facets',
    examples: 'examples',
  },
};
