/* eslint-disable */
/**
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import {
  IntegerEnum,
  IntegerEnumOneValue,
  IntegerEnumWithDefaultValue,
  StringEnum,
  StringEnumWithDefaultValue,
} from './';

/**
 *
 * @interface EnumTest
 */
export interface EnumTest {
  /**
   *
   * @type {string}
   * @memberof EnumTest
   */
  enumString?: EnumTestEnumStringEnum;

  /**
   *
   * @type {string}
   * @memberof EnumTest
   */
  enumStringRequired: EnumTestEnumStringRequiredEnum;

  /**
   *
   * @type {number}
   * @memberof EnumTest
   */
  enumInteger?: EnumTestEnumIntegerEnum;

  /**
   *
   * @type {number}
   * @memberof EnumTest
   */
  enumNumber?: EnumTestEnumNumberEnum;

  /**
   *
   * @type {StringEnum}
   * @memberof EnumTest
   */
  stringEnum?: StringEnum | null;

  /**
   *
   * @type {IntegerEnum}
   * @memberof EnumTest
   */
  integerEnum?: IntegerEnum;

  /**
   *
   * @type {StringEnumWithDefaultValue}
   * @memberof EnumTest
   */
  stringEnumWithDefaultValue?: StringEnumWithDefaultValue;

  /**
   *
   * @type {IntegerEnumWithDefaultValue}
   * @memberof EnumTest
   */
  integerEnumWithDefaultValue?: IntegerEnumWithDefaultValue;

  /**
   *
   * @type {IntegerEnumOneValue}
   * @memberof EnumTest
   */
  integerEnumOneValue?: IntegerEnumOneValue;
}

export const EnumTestModel: GenericModel = {
  classname: 'EnumTest',
  type: 'generic',
  parent: undefined,
  vars: {
    enumString: [
      'enumString', // name
      'enum_string', // baseName
      'string', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      true, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      true, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    enumStringRequired: [
      'enumStringRequired', // name
      'enum_string_required', // baseName
      'string', // datatype
      true, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      true, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      true, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    enumInteger: [
      'enumInteger', // name
      'enum_integer', // baseName
      'number', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      true, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      true, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      true, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    enumNumber: [
      'enumNumber', // name
      'enum_number', // baseName
      'number', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      true, // isDouble
      false, // isEmail
      true, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      true, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    stringEnum: [
      'stringEnum', // name
      'stringEnum', // baseName
      'StringEnum', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      true, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    integerEnum: [
      'integerEnum', // name
      'IntegerEnum', // baseName
      'IntegerEnum', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    stringEnumWithDefaultValue: [
      'stringEnumWithDefaultValue', // name
      'StringEnumWithDefaultValue', // baseName
      'StringEnumWithDefaultValue', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    integerEnumWithDefaultValue: [
      'integerEnumWithDefaultValue', // name
      'IntegerEnumWithDefaultValue', // baseName
      'IntegerEnumWithDefaultValue', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    integerEnumOneValue: [
      'integerEnumOneValue', // name
      'IntegerEnumOneValue', // baseName
      'IntegerEnumOneValue', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    enumString: 'enum_string',
    enumStringRequired: 'enum_string_required',
    enumInteger: 'enum_integer',
    enumNumber: 'enum_number',
    stringEnum: 'stringEnum',
    integerEnum: 'IntegerEnum',
    stringEnumWithDefaultValue: 'StringEnumWithDefaultValue',
    integerEnumWithDefaultValue: 'IntegerEnumWithDefaultValue',
    integerEnumOneValue: 'IntegerEnumOneValue',
  },
};

/**
 * @enum {string}
 */
export enum EnumTestEnumStringEnum {
  UPPER = 'UPPER',
  Lower = 'lower',
  Empty = '',
}
/**
 * @enum {string}
 */
export enum EnumTestEnumStringRequiredEnum {
  UPPER = 'UPPER',
  Lower = 'lower',
  Empty = '',
}
/**
 * @enum {string}
 */
export enum EnumTestEnumIntegerEnum {
  NUMBER_1 = 1,
  NUMBER_MINUS_1 = -1,
}
/**
 * @enum {string}
 */
export enum EnumTestEnumNumberEnum {
  NUMBER_1_DOT_1 = 1.1,
  NUMBER_MINUS_1_DOT_2 = -1.2,
}
