/* eslint-disable */
/**
 * MultipartFile test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

/**
 *
 * @interface InlineObject1
 */
export interface InlineObject1 {
  /**
   * One file
   * @type {Blob}
   * @memberof InlineObject1
   */
  file?: Blob;
}

export const InlineObject1Model: GenericModel = {
  classname: 'InlineObject1',
  type: 'generic',
  parent: undefined,
  vars: {
    file: {
      name: 'file',
      baseName: 'file',
      datatype: 'Blob',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: true,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: true,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    file: 'file',
  },
};
