/* eslint-disable */
/**
 * Swift 5 Test Schema
 * This is a test schema which exercises Swagger schema features for testing the swift5 language codegen module.
 *
 * The version of the OpenAPI document: 1.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { BaseCard, PlaceCardAllOf } from './';

/**
 * This is a card object for a Person derived from BaseCard.
 * @interface PlaceCard
 */
export interface PlaceCard extends BaseCard {
  /**
   *
   * @type {string}
   * @memberof PlaceCard
   */
  placeName?: string;

  /**
   *
   * @type {string}
   * @memberof PlaceCard
   */
  placeAddress?: string;
}

export const PlaceCardModel: GenericModel = {
  classname: 'PlaceCard',
  type: 'generic',
  parent: 'BaseCard',
  vars: {
    placeName: {
      name: 'placeName',
      baseName: 'placeName',
      datatype: 'string',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    placeAddress: {
      name: 'placeAddress',
      baseName: 'placeAddress',
      datatype: 'string',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    placeName: 'placeName',
    placeAddress: 'placeAddress',
  },
};
