/* eslint-disable */
/**
 * Multipart OpenAPI V3 Rust Server Test
 * API under test
 *
 * The version of the OpenAPI document: 1.0.7
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

/**
 *
 * @interface InlineObject
 */
export interface InlineObject {
  /**
   *
   * @type {Blob}
   * @memberof InlineObject
   */
  binary1?: Blob;

  /**
   *
   * @type {Blob}
   * @memberof InlineObject
   */
  binary2?: Blob;
}

export const InlineObjectModel: GenericModel = {
  classname: 'InlineObject',
  type: 'generic',
  parent: undefined,
  vars: {
    binary1: [
      'binary1', // name
      'binary1', // baseName
      'Blob', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      true, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      true, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    binary2: [
      'binary2', // name
      'binary2', // baseName
      'Blob', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      true, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      true, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    binary1: 'binary1',
    binary2: 'binary2',
  },
};
