/* eslint-disable */
/**
 * OpenAPI Petstore *_/ \' \" =end -- \\r\\n \\n \\r
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  *_/ \' \" =end --
 *
 * The version of the OpenAPI document: 1.0.0 *_/ \' \" =end -- \\r\\n \\n \\r
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { ReturnModel } from './models/Return';

export const typeSerializer = new TypeSerializer({
  Return: ReturnModel,
});
