/* eslint-disable */
/**
 * fruity
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { OneOfModel } from '@rocket-scripts/openapi';

import { Apple, Banana } from './';

/**
 * @type Fruit
 *
 */
export type Fruit = Apple | Banana;

export const FruitModel: OneOfModel = {
  classname: 'Fruit',
  type: 'oneOf',
  oneOf: ['Apple', 'Banana'],
};
