/* eslint-disable */
/**
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { AdditionalPropertiesAnyTypeModel } from './models/AdditionalPropertiesAnyType';
import { AdditionalPropertiesArrayModel } from './models/AdditionalPropertiesArray';
import { AdditionalPropertiesBooleanModel } from './models/AdditionalPropertiesBoolean';
import { AdditionalPropertiesClassModel } from './models/AdditionalPropertiesClass';
import { AdditionalPropertiesIntegerModel } from './models/AdditionalPropertiesInteger';
import { AdditionalPropertiesNumberModel } from './models/AdditionalPropertiesNumber';
import { AdditionalPropertiesObjectModel } from './models/AdditionalPropertiesObject';
import { AdditionalPropertiesStringModel } from './models/AdditionalPropertiesString';
import { AnimalModel } from './models/Animal';
import { ArrayOfArrayOfNumberOnlyModel } from './models/ArrayOfArrayOfNumberOnly';
import { ArrayOfNumberOnlyModel } from './models/ArrayOfNumberOnly';
import { ArrayTestModel } from './models/ArrayTest';
import { BigCatModel } from './models/BigCat';
import { BigCatAllOfModel } from './models/BigCatAllOf';
import { CapitalizationModel } from './models/Capitalization';
import { CatModel } from './models/Cat';
import { CatAllOfModel } from './models/CatAllOf';
import { CategoryModel } from './models/Category';
import { ClassModelModel } from './models/ClassModel';
import { ClientModel } from './models/Client';
import { DogModel } from './models/Dog';
import { DogAllOfModel } from './models/DogAllOf';
import { EnumArraysModel } from './models/EnumArrays';
import { EnumClassModel } from './models/EnumClass';
import { EnumTestModel } from './models/EnumTest';
import { FileSchemaTestClassModel } from './models/FileSchemaTestClass';
import { FormatTestModel } from './models/FormatTest';
import { HasOnlyReadOnlyModel } from './models/HasOnlyReadOnly';
import { ListModel } from './models/List';
import { MapTestModel } from './models/MapTest';
import { MixedPropertiesAndAdditionalPropertiesClassModel } from './models/MixedPropertiesAndAdditionalPropertiesClass';
import { Model200ResponseModel } from './models/Model200Response';
import { ModelApiResponseModel } from './models/ModelApiResponse';
import { ModelFileModel } from './models/ModelFile';
import { NameModel } from './models/Name';
import { NumberOnlyModel } from './models/NumberOnly';
import { OrderModel } from './models/Order';
import { OuterCompositeModel } from './models/OuterComposite';
import { OuterEnumModel } from './models/OuterEnum';
import { PetModel } from './models/Pet';
import { ReadOnlyFirstModel } from './models/ReadOnlyFirst';
import { ReturnModel } from './models/Return';
import { SpecialModelNameModel } from './models/SpecialModelName';
import { TagModel } from './models/Tag';
import { TypeHolderDefaultModel } from './models/TypeHolderDefault';
import { TypeHolderExampleModel } from './models/TypeHolderExample';
import { UserModel } from './models/User';
import { XmlItemModel } from './models/XmlItem';

export const typeSerializer = new TypeSerializer({
  AdditionalPropertiesAnyType: AdditionalPropertiesAnyTypeModel,
  AdditionalPropertiesArray: AdditionalPropertiesArrayModel,
  AdditionalPropertiesBoolean: AdditionalPropertiesBooleanModel,
  AdditionalPropertiesClass: AdditionalPropertiesClassModel,
  AdditionalPropertiesInteger: AdditionalPropertiesIntegerModel,
  AdditionalPropertiesNumber: AdditionalPropertiesNumberModel,
  AdditionalPropertiesObject: AdditionalPropertiesObjectModel,
  AdditionalPropertiesString: AdditionalPropertiesStringModel,
  Animal: AnimalModel,
  ArrayOfArrayOfNumberOnly: ArrayOfArrayOfNumberOnlyModel,
  ArrayOfNumberOnly: ArrayOfNumberOnlyModel,
  ArrayTest: ArrayTestModel,
  BigCat: BigCatModel,
  BigCatAllOf: BigCatAllOfModel,
  Capitalization: CapitalizationModel,
  Cat: CatModel,
  CatAllOf: CatAllOfModel,
  Category: CategoryModel,
  ClassModel: ClassModelModel,
  Client: ClientModel,
  Dog: DogModel,
  DogAllOf: DogAllOfModel,
  EnumArrays: EnumArraysModel,
  EnumClass: EnumClassModel,
  EnumTest: EnumTestModel,
  FileSchemaTestClass: FileSchemaTestClassModel,
  FormatTest: FormatTestModel,
  HasOnlyReadOnly: HasOnlyReadOnlyModel,
  List: ListModel,
  MapTest: MapTestModel,
  MixedPropertiesAndAdditionalPropertiesClass: MixedPropertiesAndAdditionalPropertiesClassModel,
  Model200Response: Model200ResponseModel,
  ModelApiResponse: ModelApiResponseModel,
  ModelFile: ModelFileModel,
  Name: NameModel,
  NumberOnly: NumberOnlyModel,
  Order: OrderModel,
  OuterComposite: OuterCompositeModel,
  OuterEnum: OuterEnumModel,
  Pet: PetModel,
  ReadOnlyFirst: ReadOnlyFirstModel,
  Return: ReturnModel,
  SpecialModelName: SpecialModelNameModel,
  Tag: TagModel,
  TypeHolderDefault: TypeHolderDefaultModel,
  TypeHolderExample: TypeHolderExampleModel,
  User: UserModel,
  XmlItem: XmlItemModel,
});
