/* eslint-disable */
/**
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

/**
 *
 * @interface MapTest
 */
export interface MapTest {
  /**
   *
   * @type {{ [key: string]: { [key: string]: string; }; }}
   * @memberof MapTest
   */
  mapMapOfString?: { [key: string]: { [key: string]: string } };

  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof MapTest
   */
  mapOfEnumString?: { [key: string]: string };

  /**
   *
   * @type {{ [key: string]: boolean; }}
   * @memberof MapTest
   */
  directMap?: { [key: string]: boolean };

  /**
   *
   * @type {{ [key: string]: boolean; }}
   * @memberof MapTest
   */
  indirectMap?: { [key: string]: boolean };
}

export const MapTestModel: GenericModel = {
  classname: 'MapTest',
  type: 'generic',
  parent: undefined,
  vars: {
    mapMapOfString: [
      'mapMapOfString', // name
      'map_map_of_string', // baseName
      '{ [key: string]: { [key: string]: string; }; }', // datatype
      false, // required
      '{ [key: string]: string; }', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      true, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    mapOfEnumString: [
      'mapOfEnumString', // name
      'map_of_enum_string', // baseName
      '{ [key: string]: string; }', // datatype
      false, // required
      'string', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      true, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      true, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    directMap: [
      'directMap', // name
      'direct_map', // baseName
      '{ [key: string]: boolean; }', // datatype
      false, // required
      'boolean', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      true, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    indirectMap: [
      'indirectMap', // name
      'indirect_map', // baseName
      '{ [key: string]: boolean; }', // datatype
      false, // required
      'boolean', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      true, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    mapMapOfString: 'map_map_of_string',
    mapOfEnumString: 'map_of_enum_string',
    directMap: 'direct_map',
    indirectMap: 'indirect_map',
  },
};

/**
 * @enum {string}
 */
export enum MapTestMapOfEnumStringEnum {
  UPPER = 'UPPER',
  Lower = 'lower',
}
