/* eslint-disable */
/**
 * time@work rest api
 * internal rest api, used by time@work angular client
 *
 * The version of the OpenAPI document: 0.1
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { ResponseStatusExceptionMostSpecificCauseStackTrace } from './';

/**
 *
 * @interface ResponseStatusExceptionMostSpecificCauseSuppressed
 */
export interface ResponseStatusExceptionMostSpecificCauseSuppressed {
  /**
   *
   * @type {Array<ResponseStatusExceptionMostSpecificCauseStackTrace>}
   * @memberof ResponseStatusExceptionMostSpecificCauseSuppressed
   */
  stackTrace?: Array<ResponseStatusExceptionMostSpecificCauseStackTrace>;

  /**
   *
   * @type {string}
   * @memberof ResponseStatusExceptionMostSpecificCauseSuppressed
   */
  message?: string;

  /**
   *
   * @type {string}
   * @memberof ResponseStatusExceptionMostSpecificCauseSuppressed
   */
  localizedMessage?: string;
}

export const ResponseStatusExceptionMostSpecificCauseSuppressedModel: GenericModel = {
  classname: 'ResponseStatusExceptionMostSpecificCauseSuppressed',
  type: 'generic',
  parent: undefined,
  vars: {
    stackTrace: [
      'stackTrace', // name
      'stackTrace', // baseName
      'Array&lt;ResponseStatusExceptionMostSpecificCauseStackTrace&gt;', // datatype
      false, // required
      'ResponseStatusExceptionMostSpecificCauseStackTrace', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      true, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    message: [
      'message', // name
      'message', // baseName
      'string', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      true, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
    localizedMessage: [
      'localizedMessage', // name
      'localizedMessage', // baseName
      'string', // datatype
      false, // required
      undefined, // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      false, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      false, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      true, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      true, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    stackTrace: 'stackTrace',
    message: 'message',
    localizedMessage: 'localizedMessage',
  },
};
