/* eslint-disable */
/**
 * rust-server-test
 * This spec is for testing rust-server-specific things
 *
 * The version of the OpenAPI document: 2.3.4
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

/**
 *
 * @interface ANullableContainer
 */
export interface ANullableContainer {
  /**
   *
   * @type {string}
   * @memberof ANullableContainer
   */
  nullableThing?: string | null;

  /**
   *
   * @type {string}
   * @memberof ANullableContainer
   */
  requiredNullableThing: string | null;
}

export const ANullableContainerModel: GenericModel = {
  classname: 'ANullableContainer',
  type: 'generic',
  parent: undefined,
  vars: {
    nullableThing: {
      name: 'nullableThing',
      baseName: 'NullableThing',
      datatype: 'string',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: true,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    requiredNullableThing: {
      name: 'requiredNullableThing',
      baseName: 'RequiredNullableThing',
      datatype: 'string',
      required: true,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: true,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    nullableThing: 'NullableThing',
    requiredNullableThing: 'RequiredNullableThing',
  },
};
