/* eslint-disable */
/**
 * rust-server-test
 * This spec is for testing rust-server-specific things
 *
 * The version of the OpenAPI document: 2.3.4
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { ObjectOfObjectsInner } from './';

/**
 * An object of objects
 * @interface ObjectOfObjects
 */
export interface ObjectOfObjects {
  /**
   *
   * @type {ObjectOfObjectsInner}
   * @memberof ObjectOfObjects
   */
  inner?: ObjectOfObjectsInner;
}

export const ObjectOfObjectsModel: GenericModel = {
  classname: 'ObjectOfObjects',
  type: 'generic',
  parent: undefined,
  vars: {
    inner: {
      name: 'inner',
      baseName: 'inner',
      datatype: 'ObjectOfObjectsInner',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: true,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    inner: 'inner',
  },
};
