/* eslint-disable */
/**
 * OpenAPI
 * Test
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { Baz } from './';

/**
 *
 * @interface Bar
 */
export interface Bar {
  /**
   *
   * @type {Baz}
   * @memberof Bar
   */
  baz?: Baz;
}

export const BarModel: GenericModel = {
  classname: 'Bar',
  type: 'generic',
  parent: undefined,
  vars: {
    baz: {
      name: 'baz',
      baseName: 'baz',
      datatype: 'Baz',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: true,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    baz: 'baz',
  },
};
