/* eslint-disable */
/**
 * OpenAPI Petstore
 * Test for issue 4062
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { EnumModel } from '@rocket-scripts/openapi';

/**
 * An enum with complex-ish naming
 * @enum {string}
 */
export enum PetEnum {
  MyFirstValue = 'myFirstValue',
  MYSECONDVALUE = 'MY_SECOND_VALUE',
}

export const PetEnumModel: EnumModel = {
  classname: 'PetEnum',
  type: 'enum',
  enumVars: new Set(['myFirstValue', 'MY_SECOND_VALUE']),
};
