/* eslint-disable */
/**
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

/**
 *
 * @interface EnumArrays
 */
export interface EnumArrays {
  /**
   *
   * @type {string}
   * @memberof EnumArrays
   */
  justSymbol?: EnumArraysJustSymbolEnum;

  /**
   *
   * @type {Array<string>}
   * @memberof EnumArrays
   */
  arrayEnum?: Array<EnumArraysArrayEnumEnum>;
}

export const EnumArraysModel: GenericModel = {
  classname: 'EnumArrays',
  type: 'generic',
  parent: undefined,
  vars: {
    justSymbol: {
      name: 'justSymbol',
      baseName: 'just_symbol',
      datatype: 'string',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: true,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    arrayEnum: {
      name: 'arrayEnum',
      baseName: 'array_enum',
      datatype: 'Array&lt;string&gt;',
      required: false,
      itemsDataType: 'string',
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: true,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: true,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: true,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    justSymbol: 'just_symbol',
    arrayEnum: 'array_enum',
  },
};

/**
 * @enum {string}
 */
export enum EnumArraysJustSymbolEnum {
  GreaterThanOrEqualTo = '>=',
  Dollar = '$',
}
/**
 * @enum {string}
 */
export enum EnumArraysArrayEnumEnum {
  Fish = 'fish',
  Crab = 'crab',
}
