/* eslint-disable */
/**
 * Test API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { TimeListEntry } from './';

/**
 *
 * @interface MessageEventCoreWithTimeListEntriesAllOf
 */
export interface MessageEventCoreWithTimeListEntriesAllOf {
  /**
   *
   * @type {Array<TimeListEntry>}
   * @memberof MessageEventCoreWithTimeListEntriesAllOf
   */
  timeListEntries: Array<TimeListEntry>;
}

export const MessageEventCoreWithTimeListEntriesAllOfModel: GenericModel = {
  classname: 'MessageEventCoreWithTimeListEntriesAllOf',
  type: 'generic',
  parent: undefined,
  vars: {
    timeListEntries: [
      'timeListEntries', // name
      'timeListEntries', // baseName
      'Array&lt;TimeListEntry&gt;', // datatype
      true, // required
      'TimeListEntry', // itemsDataType
      false, // isAnyType
      false, // isBinary
      false, // isBoolean
      false, // isByteArray
      false, // isCircularReference
      true, // isContainer
      false, // isDate
      false, // isDateTime
      false, // isDiscriminator
      false, // isDouble
      false, // isEmail
      false, // isEnum
      false, // isFile
      false, // isFloat
      false, // isFreeFormObject
      false, // isInherited
      false, // isInteger
      true, // isListContainer
      false, // isLong
      false, // isMapContainer
      false, // isModel
      false, // isNullable
      false, // isNumber
      false, // isNumeric
      false, // isPrimitiveType
      false, // isReadOnly
      false, // isSelfReference
      false, // isString
      false, // isUri
      false, // isUuid
      false, // isWriteOnly
      false, // isXmlAttribute
      false, // isXmlWrapped
    ],
  },
  baseNames: {
    timeListEntries: 'timeListEntries',
  },
};
