/**
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import type {
  UrlQueryInput,
  OperationConfiguration,
  RequestConfiguration,
  ResponseConfiguration,
  FetchParameters,
} from '@rocket-scripts/openapi';
import {
  pipe,
  collectionFormats,
  querystring,
  fetchRequest,
  APIRequestError,
  APIExceptionError,
} from '@rocket-scripts/openapi';
import type {
  Client,
  FileSchemaTestClass,
  OuterComposite,
  User,
} from '../models';
import { typeSerializer } from '../runtime';

/* eslint-disable */

export interface FakeOuterBooleanSerializeRequestParameters {
  body?: boolean;
}
export interface FakeOuterCompositeSerializeRequestParameters {
  body?: OuterComposite;
}
export interface FakeOuterNumberSerializeRequestParameters {
  body?: number;
}
export interface FakeOuterStringSerializeRequestParameters {
  body?: string;
}
export interface TestBodyWithFileSchemaRequestParameters {
  body: FileSchemaTestClass;
}
export interface TestBodyWithQueryParamsRequestParameters {
  query: string;
  body: User;
}
export interface TestClientModelRequestParameters {
  body: Client;
}
export interface TestEndpointParametersRequestParameters {
  number: number;
  _double: number;
  patternWithoutDelimiter: string;
  _byte: string;
  integer?: number;
  int32?: number;
  int64?: number;
  _float?: number;
  string?: string;
  binary?: Blob;
  date?: Date;
  dateTime?: Date;
  password?: string;
  callback?: string;
}
export interface TestEnumParametersRequestParameters {
  enumHeaderStringArray?: Array<TestEnumParametersEnumHeaderStringArrayEnum>;
  enumHeaderString?: TestEnumParametersEnumHeaderStringEnum;
  enumQueryStringArray?: Array<TestEnumParametersEnumQueryStringArrayEnum>;
  enumQueryString?: TestEnumParametersEnumQueryStringEnum;
  enumQueryInteger?: TestEnumParametersEnumQueryIntegerEnum;
  enumQueryDouble?: TestEnumParametersEnumQueryDoubleEnum;
  enumFormStringArray?: Array<TestEnumParametersEnumFormStringArrayEnum>;
  enumFormString?: TestEnumParametersEnumFormStringEnum;
}
export interface TestGroupParametersRequestParameters {
  requiredStringGroup: number;
  requiredBooleanGroup: boolean;
  requiredInt64Group: number;
  stringGroup?: number;
  booleanGroup?: boolean;
  int64Group?: number;
}
export interface TestInlineAdditionalPropertiesRequestParameters {
  param: { [key: string]: string };
}
export interface TestJsonFormDataRequestParameters {
  param: string;
  param2: string;
}

/**
 * Test serialization of outer boolean types
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterBooleanSerializeRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: FakeOuterBooleanSerializeRequestParameters,
): FetchParameters => {
  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(/\/+$/, '')}/fake/outer/boolean`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = requestParameters.body as any;

  return {
    input: url,
    init: {
      method: 'POST',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * Test serialization of outer boolean types
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterBooleanSerializeResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<boolean> => {
  if (response.status >= 200 && response.status < 300) {
    return response.text().then(typeSerializer.toValueObject('boolean'));
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * Test serialization of outer boolean types
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function fakeOuterBooleanSerialize(
  requestParameters: FakeOuterBooleanSerializeRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<boolean> {
  return pipe(
    fakeOuterBooleanSerializeRequest(configuration),
    fetchRequest(configuration),
    fakeOuterBooleanSerializeResponse(configuration),
  )(requestParameters);
}

/**
 * Test serialization of object with outer number type
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterCompositeSerializeRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: FakeOuterCompositeSerializeRequestParameters,
): FetchParameters => {
  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(/\/+$/, '')}/fake/outer/composite`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = JSON.stringify(
    typeSerializer.toJsonObject('OuterComposite')(requestParameters.body),
  );

  return {
    input: url,
    init: {
      method: 'POST',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * Test serialization of object with outer number type
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterCompositeSerializeResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<OuterComposite> => {
  if (response.status >= 200 && response.status < 300) {
    return response.json().then(typeSerializer.toValueObject('OuterComposite'));
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * Test serialization of object with outer number type
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function fakeOuterCompositeSerialize(
  requestParameters: FakeOuterCompositeSerializeRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<OuterComposite> {
  return pipe(
    fakeOuterCompositeSerializeRequest(configuration),
    fetchRequest(configuration),
    fakeOuterCompositeSerializeResponse(configuration),
  )(requestParameters);
}

/**
 * Test serialization of outer number types
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterNumberSerializeRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: FakeOuterNumberSerializeRequestParameters,
): FetchParameters => {
  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(/\/+$/, '')}/fake/outer/number`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = requestParameters.body as any;

  return {
    input: url,
    init: {
      method: 'POST',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * Test serialization of outer number types
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterNumberSerializeResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<number> => {
  if (response.status >= 200 && response.status < 300) {
    return response.text().then(typeSerializer.toValueObject('number'));
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * Test serialization of outer number types
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function fakeOuterNumberSerialize(
  requestParameters: FakeOuterNumberSerializeRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<number> {
  return pipe(
    fakeOuterNumberSerializeRequest(configuration),
    fetchRequest(configuration),
    fakeOuterNumberSerializeResponse(configuration),
  )(requestParameters);
}

/**
 * Test serialization of outer string types
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterStringSerializeRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: FakeOuterStringSerializeRequestParameters,
): FetchParameters => {
  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(/\/+$/, '')}/fake/outer/string`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = requestParameters.body as any;

  return {
    input: url,
    init: {
      method: 'POST',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * Test serialization of outer string types
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const fakeOuterStringSerializeResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<string> => {
  if (response.status >= 200 && response.status < 300) {
    return response.text().then(typeSerializer.toValueObject('string'));
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * Test serialization of outer string types
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function fakeOuterStringSerialize(
  requestParameters: FakeOuterStringSerializeRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<string> {
  return pipe(
    fakeOuterStringSerializeRequest(configuration),
    fetchRequest(configuration),
    fakeOuterStringSerializeResponse(configuration),
  )(requestParameters);
}

/**
 * For this test, the body for this request much reference a schema named `File`.
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testBodyWithFileSchemaRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestBodyWithFileSchemaRequestParameters,
): FetchParameters => {
  if (requestParameters.body === null || requestParameters.body === undefined) {
    throw new APIRequestError(
      `Required parameter requestParameters.body was null or undefined when calling testBodyWithFileSchema.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(
    /\/+$/,
    '',
  )}/fake/body-with-file-schema`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = JSON.stringify(
    typeSerializer.toJsonObject('FileSchemaTestClass')(requestParameters.body),
  );

  return {
    input: url,
    init: {
      method: 'PUT',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * For this test, the body for this request much reference a schema named `File`.
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testBodyWithFileSchemaResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * For this test, the body for this request much reference a schema named `File`.
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testBodyWithFileSchema(
  requestParameters: TestBodyWithFileSchemaRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testBodyWithFileSchemaRequest(configuration),
    fetchRequest(configuration),
    testBodyWithFileSchemaResponse(configuration),
  )(requestParameters);
}

/**
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testBodyWithQueryParamsRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestBodyWithQueryParamsRequestParameters,
): FetchParameters => {
  if (
    requestParameters.query === null ||
    requestParameters.query === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.query was null or undefined when calling testBodyWithQueryParams.`,
    );
  }
  if (requestParameters.body === null || requestParameters.body === undefined) {
    throw new APIRequestError(
      `Required parameter requestParameters.body was null or undefined when calling testBodyWithQueryParams.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  if (requestParameters.query !== undefined) {
    queryParameters['query'] = requestParameters.query;
  }

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(
    /\/+$/,
    '',
  )}/fake/body-with-query-params`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = JSON.stringify(
    typeSerializer.toJsonObject('User')(requestParameters.body),
  );

  return {
    input: url,
    init: {
      method: 'PUT',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testBodyWithQueryParamsResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testBodyWithQueryParams(
  requestParameters: TestBodyWithQueryParamsRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testBodyWithQueryParamsRequest(configuration),
    fetchRequest(configuration),
    testBodyWithQueryParamsResponse(configuration),
  )(requestParameters);
}

/**
 * To test \"client\" model
 * To test \"client\" model
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testClientModelRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestClientModelRequestParameters,
): FetchParameters => {
  if (requestParameters.body === null || requestParameters.body === undefined) {
    throw new APIRequestError(
      `Required parameter requestParameters.body was null or undefined when calling testClientModel.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(/\/+$/, '')}/fake`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = JSON.stringify(
    typeSerializer.toJsonObject('Client')(requestParameters.body),
  );

  return {
    input: url,
    init: {
      method: 'PATCH',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * To test \"client\" model
 * To test \"client\" model
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testClientModelResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<Client> => {
  if (response.status >= 200 && response.status < 300) {
    return response.json().then(typeSerializer.toValueObject('Client'));
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * To test \"client\" model
 * To test \"client\" model
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testClientModel(
  requestParameters: TestClientModelRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<Client> {
  return pipe(
    testClientModelRequest(configuration),
    fetchRequest(configuration),
    testClientModelResponse(configuration),
  )(requestParameters);
}

/**
 * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트
 * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testEndpointParametersRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestEndpointParametersRequestParameters,
): FetchParameters => {
  if (
    requestParameters.number === null ||
    requestParameters.number === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.number was null or undefined when calling testEndpointParameters.`,
    );
  }
  if (
    requestParameters._double === null ||
    requestParameters._double === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters._double was null or undefined when calling testEndpointParameters.`,
    );
  }
  if (
    requestParameters.patternWithoutDelimiter === null ||
    requestParameters.patternWithoutDelimiter === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.patternWithoutDelimiter was null or undefined when calling testEndpointParameters.`,
    );
  }
  if (
    requestParameters._byte === null ||
    requestParameters._byte === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters._byte was null or undefined when calling testEndpointParameters.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  if (username !== undefined || password !== undefined) {
    headerParameters.set(
      'Authorization',
      'Basic ' + btoa(username + ':' + password),
    );
  }

  let formParams: FormData | URLSearchParams;
  let useForm = false;

  // use FormData to transmit files using content-type "multipart/form-data"
  useForm = [{ contentType: 'application/x-www-form-urlencoded' }].some(
    ({ contentType }) => contentType === 'multipart/form-data',
  );

  if (useForm) {
    formParams = new FormData();
  } else {
    formParams = new URLSearchParams();
  }

  if (requestParameters.integer !== undefined) {
    formParams.append('integer', requestParameters.integer as any);
  }
  if (requestParameters.int32 !== undefined) {
    formParams.append('int32', requestParameters.int32 as any);
  }
  if (requestParameters.int64 !== undefined) {
    formParams.append('int64', requestParameters.int64 as any);
  }
  if (requestParameters.number !== undefined) {
    formParams.append('number', requestParameters.number as any);
  }
  if (requestParameters._float !== undefined) {
    formParams.append('float', requestParameters._float as any);
  }
  if (requestParameters._double !== undefined) {
    formParams.append('double', requestParameters._double as any);
  }
  if (requestParameters.string !== undefined) {
    formParams.append('string', requestParameters.string as any);
  }
  if (requestParameters.patternWithoutDelimiter !== undefined) {
    formParams.append(
      'pattern_without_delimiter',
      requestParameters.patternWithoutDelimiter as any,
    );
  }
  if (requestParameters._byte !== undefined) {
    formParams.append('byte', requestParameters._byte as any);
  }
  if (requestParameters.binary !== undefined) {
    formParams.append('binary', requestParameters.binary as any);
  }
  if (requestParameters.date !== undefined) {
    formParams.append('date', requestParameters.date as any);
  }
  if (requestParameters.dateTime !== undefined) {
    formParams.append('dateTime', requestParameters.dateTime as any);
  }
  if (requestParameters.password !== undefined) {
    formParams.append('password', requestParameters.password as any);
  }
  if (requestParameters.callback !== undefined) {
    formParams.append('callback', requestParameters.callback as any);
  }

  let url: string = `${basePath.replace(/\/+$/, '')}/fake`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = formParams;

  return {
    input: url,
    init: {
      method: 'POST',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트
 * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testEndpointParametersResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트
 * Fake endpoint for testing various parameters  假端點  偽のエンドポイント  가짜 엔드 포인트
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testEndpointParameters(
  requestParameters: TestEndpointParametersRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testEndpointParametersRequest(configuration),
    fetchRequest(configuration),
    testEndpointParametersResponse(configuration),
  )(requestParameters);
}

/**
 * To test enum parameters
 * To test enum parameters
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testEnumParametersRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestEnumParametersRequestParameters,
): FetchParameters => {
  const queryParameters: UrlQueryInput = {};

  if (requestParameters.enumQueryStringArray) {
    queryParameters[
      'enum_query_string_array'
    ] = requestParameters.enumQueryStringArray.join(collectionFormats['csv']);
  }
  if (requestParameters.enumQueryString !== undefined) {
    queryParameters['enum_query_string'] = requestParameters.enumQueryString;
  }
  if (requestParameters.enumQueryInteger !== undefined) {
    queryParameters['enum_query_integer'] = requestParameters.enumQueryInteger;
  }
  if (requestParameters.enumQueryDouble !== undefined) {
    queryParameters['enum_query_double'] = requestParameters.enumQueryDouble;
  }

  const headerParameters: Headers = new Headers(headers);

  if (requestParameters.enumHeaderStringArray) {
    headerParameters.set(
      'enum_header_string_array',
      requestParameters.enumHeaderStringArray.join(collectionFormats['csv']),
    );
  }
  if (
    requestParameters.enumHeaderString !== undefined &&
    requestParameters.enumHeaderString !== null
  ) {
    headerParameters.set(
      'enum_header_string',
      String(requestParameters.enumHeaderString),
    );
  }

  let formParams: FormData | URLSearchParams;
  let useForm = false;

  if (useForm) {
    formParams = new FormData();
  } else {
    formParams = new URLSearchParams();
  }

  if (requestParameters.enumFormStringArray) {
    formParams.append(
      'enum_form_string_array',
      requestParameters.enumFormStringArray.join(collectionFormats['csv']),
    );
  }

  if (requestParameters.enumFormString !== undefined) {
    formParams.append(
      'enum_form_string',
      requestParameters.enumFormString as any,
    );
  }

  let url: string = `${basePath.replace(/\/+$/, '')}/fake`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = formParams;

  return {
    input: url,
    init: {
      method: 'GET',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * To test enum parameters
 * To test enum parameters
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testEnumParametersResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * To test enum parameters
 * To test enum parameters
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testEnumParameters(
  requestParameters: TestEnumParametersRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testEnumParametersRequest(configuration),
    fetchRequest(configuration),
    testEnumParametersResponse(configuration),
  )(requestParameters);
}

/**
 * Fake endpoint to test group parameters (optional)
 * Fake endpoint to test group parameters (optional)
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testGroupParametersRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestGroupParametersRequestParameters,
): FetchParameters => {
  if (
    requestParameters.requiredStringGroup === null ||
    requestParameters.requiredStringGroup === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.requiredStringGroup was null or undefined when calling testGroupParameters.`,
    );
  }
  if (
    requestParameters.requiredBooleanGroup === null ||
    requestParameters.requiredBooleanGroup === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.requiredBooleanGroup was null or undefined when calling testGroupParameters.`,
    );
  }
  if (
    requestParameters.requiredInt64Group === null ||
    requestParameters.requiredInt64Group === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.requiredInt64Group was null or undefined when calling testGroupParameters.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  if (requestParameters.requiredStringGroup !== undefined) {
    queryParameters['required_string_group'] =
      requestParameters.requiredStringGroup;
  }
  if (requestParameters.requiredInt64Group !== undefined) {
    queryParameters['required_int64_group'] =
      requestParameters.requiredInt64Group;
  }
  if (requestParameters.stringGroup !== undefined) {
    queryParameters['string_group'] = requestParameters.stringGroup;
  }
  if (requestParameters.int64Group !== undefined) {
    queryParameters['int64_group'] = requestParameters.int64Group;
  }

  const headerParameters: Headers = new Headers(headers);

  if (
    requestParameters.requiredBooleanGroup !== undefined &&
    requestParameters.requiredBooleanGroup !== null
  ) {
    headerParameters.set(
      'required_boolean_group',
      String(requestParameters.requiredBooleanGroup),
    );
  }
  if (
    requestParameters.booleanGroup !== undefined &&
    requestParameters.booleanGroup !== null
  ) {
    headerParameters.set(
      'boolean_group',
      String(requestParameters.booleanGroup),
    );
  }

  let url: string = `${basePath.replace(/\/+$/, '')}/fake`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = undefined;

  return {
    input: url,
    init: {
      method: 'DELETE',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * Fake endpoint to test group parameters (optional)
 * Fake endpoint to test group parameters (optional)
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testGroupParametersResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * Fake endpoint to test group parameters (optional)
 * Fake endpoint to test group parameters (optional)
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testGroupParameters(
  requestParameters: TestGroupParametersRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testGroupParametersRequest(configuration),
    fetchRequest(configuration),
    testGroupParametersResponse(configuration),
  )(requestParameters);
}

/**
 * test inline additionalProperties
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testInlineAdditionalPropertiesRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestInlineAdditionalPropertiesRequestParameters,
): FetchParameters => {
  if (
    requestParameters.param === null ||
    requestParameters.param === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.param was null or undefined when calling testInlineAdditionalProperties.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  headerParameters.set('Content-Type', 'application/json');

  let url: string = `${basePath.replace(
    /\/+$/,
    '',
  )}/fake/inline-additionalProperties`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = JSON.stringify(requestParameters.param);

  return {
    input: url,
    init: {
      method: 'POST',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * test inline additionalProperties
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testInlineAdditionalPropertiesResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * test inline additionalProperties
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testInlineAdditionalProperties(
  requestParameters: TestInlineAdditionalPropertiesRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testInlineAdditionalPropertiesRequest(configuration),
    fetchRequest(configuration),
    testInlineAdditionalPropertiesResponse(configuration),
  )(requestParameters);
}

/**
 * test json serialization of form data
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testJsonFormDataRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestJsonFormDataRequestParameters,
): FetchParameters => {
  if (
    requestParameters.param === null ||
    requestParameters.param === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.param was null or undefined when calling testJsonFormData.`,
    );
  }
  if (
    requestParameters.param2 === null ||
    requestParameters.param2 === undefined
  ) {
    throw new APIRequestError(
      `Required parameter requestParameters.param2 was null or undefined when calling testJsonFormData.`,
    );
  }

  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  let formParams: FormData | URLSearchParams;
  let useForm = false;

  if (useForm) {
    formParams = new FormData();
  } else {
    formParams = new URLSearchParams();
  }

  if (requestParameters.param !== undefined) {
    formParams.append('param', requestParameters.param as any);
  }
  if (requestParameters.param2 !== undefined) {
    formParams.append('param2', requestParameters.param2 as any);
  }

  let url: string = `${basePath.replace(/\/+$/, '')}/fake/jsonFormData`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = formParams;

  return {
    input: url,
    init: {
      method: 'GET',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * test json serialization of form data
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testJsonFormDataResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * test json serialization of form data
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testJsonFormData(
  requestParameters: TestJsonFormDataRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testJsonFormDataRequest(configuration),
    fetchRequest(configuration),
    testJsonFormDataResponse(configuration),
  )(requestParameters);
}

/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumHeaderStringArrayEnum {
  GreaterThan = '>',
  Dollar = '$',
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumHeaderStringEnum {
  Abc = '_abc',
  Efg = '-efg',
  Xyz = '(xyz)',
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumQueryStringArrayEnum {
  GreaterThan = '>',
  Dollar = '$',
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumQueryStringEnum {
  Abc = '_abc',
  Efg = '-efg',
  Xyz = '(xyz)',
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumQueryIntegerEnum {
  NUMBER_1 = 1,
  NUMBER_MINUS_2 = -2,
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumQueryDoubleEnum {
  NUMBER_1_DOT_1 = 1.1,
  NUMBER_MINUS_1_DOT_2 = -1.2,
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumFormStringArrayEnum {
  GreaterThan = '>',
  Dollar = '$',
}
/**
 * @export
 * @enum {string}
 */
export enum TestEnumParametersEnumFormStringEnum {
  Abc = '_abc',
  Efg = '-efg',
  Xyz = '(xyz)',
}
