/* eslint-disable */
/**
 * Swift 4 Test Schema
 * This is a test schema which exercises Swagger schema features for testing the swift4 language codegen module.
 *
 * The version of the OpenAPI document: 1.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

/**
 * This is a base card object which uses a 'cardType' discriminator.
 * @interface BaseCard
 */
export interface BaseCard {
  /**
   *
   * @type {string}
   * @memberof BaseCard
   */
  cardType: string;
}

export const BaseCardModel: GenericModel = {
  classname: 'BaseCard',
  type: 'generic',
  parent: undefined,
  discriminator: {
    propertyName: 'cardType',
    mappedModels: [
      { mappingName: 'PersonCard', modelName: 'PersonCard' },
      { mappingName: 'PlaceCard', modelName: 'PlaceCard' },
    ],
  },
  vars: {
    cardType: {
      name: 'cardType',
      baseName: 'cardType',
      datatype: 'string',
      required: true,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: true,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    cardType: 'cardType',
  },
};
