/* eslint-disable */
/**
 * time@work rest api
 * internal rest api, used by time@work angular client
 *
 * The version of the OpenAPI document: 0.1
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { AuthenticationRequestModel } from './models/AuthenticationRequest';
import { AuthenticationResultModel } from './models/AuthenticationResult';
import { CProjectModel } from './models/CProject';
import { CTaskModel } from './models/CTask';
import { CTaskAssignmentModel } from './models/CTaskAssignment';
import { CTeamMemberModel } from './models/CTeamMember';
import { InlineResponse400Model } from './models/InlineResponse400';
import { InlineResponse4001Model } from './models/InlineResponse4001';
import { ProjectModel } from './models/Project';
import { ResponseStatusExceptionModel } from './models/ResponseStatusException';
import { ResponseStatusExceptionMostSpecificCauseModel } from './models/ResponseStatusExceptionMostSpecificCause';
import { ResponseStatusExceptionMostSpecificCauseStackTraceModel } from './models/ResponseStatusExceptionMostSpecificCauseStackTrace';
import { ResponseStatusExceptionMostSpecificCauseSuppressedModel } from './models/ResponseStatusExceptionMostSpecificCauseSuppressed';
import { ResponseStatusExceptionRootCauseModel } from './models/ResponseStatusExceptionRootCause';
import { TaskModel } from './models/Task';
import { TaskWeekModel } from './models/TaskWeek';
import { TeamMemberModel } from './models/TeamMember';
import { WorkHoursAssignedModel } from './models/WorkHoursAssigned';
import { WorkWeekModel } from './models/WorkWeek';

export const typeSerializer = new TypeSerializer({
  AuthenticationRequest: AuthenticationRequestModel,
  AuthenticationResult: AuthenticationResultModel,
  CProject: CProjectModel,
  CTask: CTaskModel,
  CTaskAssignment: CTaskAssignmentModel,
  CTeamMember: CTeamMemberModel,
  InlineResponse400: InlineResponse400Model,
  InlineResponse4001: InlineResponse4001Model,
  Project: ProjectModel,
  ResponseStatusException: ResponseStatusExceptionModel,
  ResponseStatusExceptionMostSpecificCause: ResponseStatusExceptionMostSpecificCauseModel,
  ResponseStatusExceptionMostSpecificCauseStackTrace: ResponseStatusExceptionMostSpecificCauseStackTraceModel,
  ResponseStatusExceptionMostSpecificCauseSuppressed: ResponseStatusExceptionMostSpecificCauseSuppressedModel,
  ResponseStatusExceptionRootCause: ResponseStatusExceptionRootCauseModel,
  Task: TaskModel,
  TaskWeek: TaskWeekModel,
  TeamMember: TeamMemberModel,
  WorkHoursAssigned: WorkHoursAssignedModel,
  WorkWeek: WorkWeekModel,
});
