/**
 * OpenAPI Petstore *_/ \' \" =end -- \\r\\n \\n \\r
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  *_/ \' \" =end --
 *
 * The version of the OpenAPI document: 1.0.0 *_/ \' \" =end -- \\r\\n \\n \\r
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import type {
  UrlQueryInput,
  OperationConfiguration,
  RequestConfiguration,
  ResponseConfiguration,
  FetchParameters,
} from '@rocket-scripts/openapi';
import {
  pipe,
  collectionFormats,
  querystring,
  fetchRequest,
  APIRequestError,
  APIExceptionError,
} from '@rocket-scripts/openapi';
import { typeSerializer } from '../runtime';

/* eslint-disable */

export interface TestCodeInjectEndRNNRRequestParameters {
  testCodeInjectEndRNNR?: string;
}

/**
 * To test code injection *_/ \' \" =end -- \\r\\n \\n \\r
 * To test code injection *_/ \' \" =end -- \\r\\n \\n \\r
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testCodeInjectEndRNNRRequest = ({
  basePath = '',
  querystringStringify = querystring,
  username,
  password,
  apiKey,
  accessToken,
  headers,
  credentials,
}: RequestConfiguration = {}) => (
  requestParameters: TestCodeInjectEndRNNRRequestParameters,
): FetchParameters => {
  const queryParameters: UrlQueryInput = {};

  const headerParameters: Headers = new Headers(headers);

  let formParams: FormData | URLSearchParams;
  let useForm = false;

  if (useForm) {
    formParams = new FormData();
  } else {
    formParams = new URLSearchParams();
  }

  if (requestParameters.testCodeInjectEndRNNR !== undefined) {
    formParams.append(
      'test code inject */ &#39; &quot; &#x3D;end -- \r\n \n \r',
      requestParameters.testCodeInjectEndRNNR as any,
    );
  }

  let url: string = `${basePath.replace(/\/+$/, '')}/fake`;
  if (queryParameters && Object.keys(queryParameters).length > 0) {
    url += '?' + querystringStringify(queryParameters);
  }

  const body = formParams;

  return {
    input: url,
    init: {
      method: 'PUT',
      headers: headerParameters,
      credentials,
      body,
    },
  };
};

/**
 * To test code injection *_/ \' \" =end -- \\r\\n \\n \\r
 * To test code injection *_/ \' \" =end -- \\r\\n \\n \\r
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export const testCodeInjectEndRNNRResponse = (
  configuration: ResponseConfiguration = {},
) => async (response: Response): Promise<void> => {
  if (response.status >= 200 && response.status < 300) {
  } else {
    switch (response.status.toString()) {
      default:
        throw response;
    }
  }
};

/**
 * To test code injection *_/ \' \" =end -- \\r\\n \\n \\r
 * To test code injection *_/ \' \" =end -- \\r\\n \\n \\r
 * @throws {APIRequestError} throw when the request is not correct
 * @throws {APIExceptionError} throw when response is out of 2xx
 * @throws {Response} throw when the response.status is not accepted (fallback throwing)
 * @throws {APISerializeError} throw when fail serialize data (include request and response)
 */
export async function testCodeInjectEndRNNR(
  requestParameters: TestCodeInjectEndRNNRRequestParameters,
  configuration: OperationConfiguration = {},
): Promise<void> {
  return pipe(
    testCodeInjectEndRNNRRequest(configuration),
    fetchRequest(configuration),
    testCodeInjectEndRNNRResponse(configuration),
  )(requestParameters);
}
