/* eslint-disable */
/**
 * Test Command model generation
 * Test Command model generation
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { ApiErrorModel } from './models/ApiError';
import { ContactModel } from './models/Contact';
import { ContactAllOfModel } from './models/ContactAllOf';
import { CustomerModel } from './models/Customer';
import { CustomerAllOfModel } from './models/CustomerAllOf';
import { CustomerTypeModel } from './models/CustomerType';
import { EntityModel } from './models/Entity';
import { OrganizationModel } from './models/Organization';
import { OrganizationAllOfModel } from './models/OrganizationAllOf';
import { PartyModel } from './models/Party';
import { PartyAllOfModel } from './models/PartyAllOf';
import { PartyTypeModel } from './models/PartyType';
import { PersonModel } from './models/Person';
import { PersonAllOfModel } from './models/PersonAllOf';

export const typeSerializer = new TypeSerializer({
  ApiError: ApiErrorModel,
  Contact: ContactModel,
  ContactAllOf: ContactAllOfModel,
  Customer: CustomerModel,
  CustomerAllOf: CustomerAllOfModel,
  CustomerType: CustomerTypeModel,
  Entity: EntityModel,
  Organization: OrganizationModel,
  OrganizationAllOf: OrganizationAllOfModel,
  Party: PartyModel,
  PartyAllOf: PartyAllOfModel,
  PartyType: PartyTypeModel,
  Person: PersonModel,
  PersonAllOf: PersonAllOfModel,
});
