/* eslint-disable */
/**
 * Test Command model generation
 * Test Command model generation
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { TypeSerializer } from '@rocket-scripts/openapi';

import { ApiErrorModel } from './models/ApiError';
import { CommandModel } from './models/Command';
import { RealCommandModel } from './models/RealCommand';

export const typeSerializer = new TypeSerializer({
  ApiError: ApiErrorModel,
  Command: CommandModel,
  RealCommand: RealCommandModel,
});
