'@rocket-scripts/openapi':
  version: 0.2.0
  tag: latest
  module: commonjs
  packageJson:
    bin:
      'openapi-typescript-generator': ./bin/openapi-typescript-generator.js
      'apigen': ./bin/openapi-typescript-generator.js
    keywords:
      - openapi
      - openapi-generator
      - typescript
'@rocket-scripts/*':
  version: 0.2.0
  tag: latest
  module: commonjs