/* eslint-disable */
/**
 * Test Command model generation
 * Test Command model generation
 *
 * The version of the OpenAPI document: 1.0.0
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import { GenericModel } from '@rocket-scripts/openapi';

import { CustomerType } from './';

/**
 *
 * @interface CustomerAllOf
 */
export interface CustomerAllOf {
  /**
   *
   * @type {CustomerType}
   * @memberof CustomerAllOf
   */
  customerType: CustomerType;

  /**
   *
   * @type {string}
   * @memberof CustomerAllOf
   */
  customerNum?: string;

  /**
   *
   * @type {string}
   * @memberof CustomerAllOf
   */
  externalCustomerNum?: string;
}

export const CustomerAllOfModel: GenericModel = {
  classname: 'CustomerAllOf',
  type: 'generic',
  parent: undefined,
  discriminator: {
    propertyName: 'customerType',
    mappedModels: [
      { mappingName: 'Customer', modelName: 'Customer' },
      { mappingName: 'customer', modelName: 'Customer' },
      { mappingName: 'Person', modelName: 'Person' },
      { mappingName: 'person', modelName: 'Person' },
      { mappingName: 'Organization', modelName: 'Organization' },
      { mappingName: 'organization', modelName: 'Organization' },
    ],
  },
  vars: {
    customerType: {
      name: 'customerType',
      baseName: 'customer_type',
      datatype: 'CustomerType',
      required: true,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: true,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: false,
      isReadOnly: false,
      isSelfReference: false,
      isString: false,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    customerNum: {
      name: 'customerNum',
      baseName: 'customer_num',
      datatype: 'string',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
    externalCustomerNum: {
      name: 'externalCustomerNum',
      baseName: 'external_customer_num',
      datatype: 'string',
      required: false,
      itemsDataType: undefined,
      isAnyType: false,
      isBinary: false,
      isBoolean: false,
      isByteArray: false,
      isCircularReference: false,
      isContainer: false,
      isDate: false,
      isDateTime: false,
      isDiscriminator: false,
      isDouble: false,
      isEmail: false,
      isEnum: false,
      isFile: false,
      isFloat: false,
      isFreeFormObject: false,
      isInherited: false,
      isInteger: false,
      isListContainer: false,
      isLong: false,
      isMapContainer: false,
      isModel: false,
      isNullable: false,
      isNumber: false,
      isNumeric: false,
      isPrimitiveType: true,
      isReadOnly: false,
      isSelfReference: false,
      isString: true,
      isUri: false,
      isUuid: false,
      isWriteOnly: false,
      isXmlAttribute: false,
      isXmlWrapped: false,
    },
  },
  baseNames: {
    customerType: 'customer_type',
    customerNum: 'customer_num',
    externalCustomerNum: 'external_customer_num',
  },
};
